apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
spec:
  finalizers:
  - kubernetes

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-data
  namespace: my-namespace
data:
  data.csv: |
    column1,column2
    value1,value2
    value3,value4

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: my-namespace
spec:
  containers:
  - name: app-container
    image: my-image
    resources:
      requests:
        memory: "400Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: my-namespace
spec:
  containers:
  - name: app-container
    image: my-image
    resources:
      requests:
        memory: "200Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  namespace: my-namespace
spec:
  containers:
  - name: app-container
    image: my-image
    resources:
      requests:
        memory: "400Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: mediawiki
  namespace: my-namespace
spec:
  containers:
  - name: app-container
    image: my-image
    volumeMounts:
      - name: data-volume
        mountPath: /data
  volumes:
    - name: data-volume
      configMap:
        name: sample-data
